name: lyf_funan_kitchen_app
description: A Flutter app for reserving kitchen slots at LYF Funan.
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  intl: ^0.19.0
  uuid: ^4.5.1
  flutter_dotenv: ^5.0.2  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
